### ISSUE TITLE
Consider the addition of an optional submission field for code URL

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/metriq-app#264]
Consider the possible addition of an optional submission field for "code URL" (as done in papers-with-code).
E.g. a paper could have both a paper URL and a GitHub URL.

**Comment by crazy4pi314** [comment]
Bumping this, would be good to have additional URL fields that can be added with a few labels (data, code, paper, other) kinda like asking for someone's various phone numbers (home, work, cell, other).

**Comment by WrathfulSpatula** [comment]
While I'm making a migration for this, I like the idea of a URL for GitHub, and I like the idea of another URL for supplementary materials, (or a DOI,) but I _don't_ like the complication to the database schema, in order to have an open-ended list of various URLs, (as I was personally considering). So, we'll add two URL fields, for GitHub and supplementary materials, but they'll just be two new columns on the `Submissions` table in the database.
