### ISSUE TITLE
Ability to delete methods

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/metriq-app#275]
We created a new method just as a test http://18.190.41.255/Method/11

It was easy to remove this from the particular submission. I wasn't able to remove it from the Method list though. 

I'm not sure we want all users to be able to do this, but it was a behavior that was different than I expected. Perhaps the user who created the method should be able to delete it? Perhaps within some time window to allow fixes for mistakes?

**Comment by WrathfulSpatula** [comment]
We could at least _hide_ any method from the index pages that has 0 submissions attached to it at the moment. The "empty" method could still be visible to drop-down selection in the submission detail modals, though. Periodically, Vincent and myself could clear any empty methods, since any user could recreate them on demand anyway. In terms of UI to delete methods, it would depend upon non-cascading foreign keys that could block the deletion functionality, and it borders on an administrative feature that I don't think member users should generally concern themselves with at all, but, if we hide methods without submissions attached, they're basically as good as gone, to administrators and users.

We might even go ahead and automatically _delete_ any methods with 0 submissions, since the modal to create a new method simultaneously immediately keys it to the contextual submission, and any deleted method could be recreated by members just as easily, this way. Either approach might be acceptable, and automatic deletion might be even better.

**Comment by WrathfulSpatula** [comment]
With hands in code, deletion seemed preferable in the abstract, but it looks like we have "soft deleted" foreign keys on methods. To track user add/delete activity, we should _not_ "hard delete" these keys like we must in order to remove a keyed method. Hence, I'm going to hide methods with 0 submissions from the methods (and tasks) indices.
