### ISSUE TITLE
Methods could be composable from parts

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/metriq-app#276]
For example when making the CLOPS submission my intuition would be that this would be the schema:

Task: "Measure CLOPS"
Method: "qiskit 0.12.1", "qiskit-runtime", "ibmq-bogota"
Result: 953

The idea is to capture the sentence, when "Measuring CLOPS" using {qiskit 0.12.1 and qiskit-runtime and ibmq-bogota} I obtain the result 953.

An interface would be to allow methods to be added like tags are added. The result is then associated to a combination of these.

**Comment by WrathfulSpatula** [comment]
In this case, I think "CLOPS" would be the "metric." The "task" is somewhat arbitrary or ambiguous, and it might be "Measure CLOPS" anyway, if "CLOPS" as a metric doesn't represent performance on a specific useful task besides a defined benchmark for CLOPS itself. Otherwise, "CLOPS" as a metric has to represent performance on a real task. I'm not saying it doesn't, but it's the application to meaningful workload that's the "task." If a benchmark suite is run for its performance results in itself, then maybe it is or isn't directly representative of a true "task," so the "task" field sounding arbitrary ends up reflecting that.

**Comment by willzeng** [comment]
This makes sense to me, Dan. Having examples in the app of this will help
guide folks.

**Comment by WrathfulSpatula** [comment]
That makes sense to me, too, Will. Also, allowing the ability to compose methods from parts, in itself, might be a good human organization tool, even if it doesn't really matter to the presentation of state-of-the-art, like it does for tasks.

**Comment by WrathfulSpatula** [comment]
Methods _are_ now composable by parts, so I think we can close this.
