### ISSUE TITLE
Include image in submission page?

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#364]
There are images that show up in the homepage for each submission (with the Metriq logo as default when none is added). I wonder if including the image also on the submission page would help provide more consistency to the reader and user, like "I am now on the right page of the submission I clicked, and this page refers to that content".

**Comment by vprusso** [comment]
I agree with this one, but I'm going to close it as we have already captured this question here.
https://github.com/unitaryfund/metriq-app/issues/249

As you and I both seem to think this is a good idea though, I'll modify https://github.com/unitaryfund/metriq-app/issues/249 to be framed as a task instead of a question. Glad to know that we're thinking similar thoughts on this :)
