### ISSUE TITLE
Detect if user is logged in before submission

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#376]
A user can fill out a full submission form, which is rejected just before clicking on "Submit" when the system does not find the user as logged in. 

This wipes out the information entered by the user, wasting their time. I suggest that the check for a logged in user should be made when clicking the first "Submit" button from the top right menu, or alternatively the submission draft could be saved and proposed to the user just after logging in.

**Comment by WrathfulSpatula** [comment]
The app actually does check if the user is logged in, first. The problem is that the cookie could expire in the meantime. Also, for security reasons, the cookie _cannot_ be directly checked for expiration, except through attempting authenticated access to an API route. Given the security considerations, I think the best we can do is to kick users back to the login page if they go directly to the submission route without a valid cookie. At that point, they have until their cookie expires to finish the submission.
