### ISSUE TITLE
Suggest tags from submission page

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#381]
Submissions, and results, can have tags. Upon making a new submission, one can insert comma-separated tags. These tags are then sorted as different tags. However, if I try to add comma-separated tags to an existing submission, these are grouped together. In the example on [this page](https://metriq.info/Submission/46), "quantum volume, honeywell" is grouped together.

**Comment by WrathfulSpatula** [comment]
This is not the intended interface. Yes, the submissions form makes use of the CSV-like nature of the API parameter, to let users enter a list of tags this way initially. However, the submission detail view has much better itemized control over tags, despite not intending to accept a comma separated list.

I understand why this might be confusing, but I need to think about what the best way to alleviate this confusion is. (I'm removing the "bug" tag, because this is working as intended.)

**Comment by nathanshammah** [comment]
I am renaming this issue. Multiple, comma-separated tags can be inserted from the submission page, when creating a new submission. However, after the first tag and comma, the suggestions are not provided any more for single tags after the first one. It seems like the suggestion considers the full string, while a new string could be considered after each comma by the advisor. As a user tends to add all tags at once, right now we risk creating duplicates with slightly different names for tags that are not the first one. 

Snapshot below for a second tag with no suggestion:
<img width="673" alt="metriq-second-tag" src="https://user-images.githubusercontent.com/14573436/160621566-73fcadec-69fd-4e59-84cb-f9367c4dbbfc.png">

**Comment by WrathfulSpatula** [comment]
This will be addressed per #600.
