### ISSUE TITLE
Export task data

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#459]
As a user, I may be interested in playing with some data myself and would find it nice to be able to export the data from a task, e.g., plots for a metric or tables. 

One suggestion could be to have a .csv export. One could think also of additional export options, e.g., pandas' `DataFrame`.

**Comment by WrathfulSpatula** [comment]
Before I invest time and effort in this, I should point out that the Python client basically can already do this. However, I see a significant barrier to access, comparing CSV download from the web vs. Python client programmatic access.

Stop me, if you think this should be the domain concern of the Python client specifically, but otherwise, I'm going ahead with a CSV export of tabulated metric values in the task detail view, at least.

**Comment by WrathfulSpatula** [comment]
I think I'll use this package, and it should be a breeze, to have this done today: https://www.npmjs.com/package/export-to-csv

**Comment by WrathfulSpatula** [comment]
The referenced code works, except the package isn't maintained, and it gives an error that the source map can't be parsed. I'll sort out the dependency issue tomorrow morning.

**Comment by nathanshammah** [comment]
Fantastic!
