### ISSUE TITLE
Larger charts from mobile

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#460]
From mobile, charts with plots render too small. 

One reason seems to be that labels "eat up space" from the charts. Having a larger default chart size could help.

One partial solution (as a user) is to rotate the phone and that increases the area of the chart. 

The markers for the legend for state of the art and data also may take up space.

**Comment by WrathfulSpatula** [comment]
We don't have an amazing set of options, here. Firstly, let's rule out horizontal scroll, because it makes for a bad mobile user experience, in my opinion. No, the simple answer is that we can't strip elements from the charts to display clearly and aesthetically in <400px of width. However, judging by the Firefox mobile browser emulator, landscape mode on the vast majority of recent mobile devices is wide enough, for sufficiently clear and aesthetic charts.

Hence, we use a CSS media query: if the screen width is less than 600px, we replace the chart with a message that tells the user their screen is too small for charts, _but they should try landscape mode_. At 600px and above, the message disappears, and the charts return, like if the user immediately just rotates their phone.

(Would we like to clearly and beautifully display all the data in the world in <200px of width, just to prove a point about design optimization? Yes, but it's not feasibly attainable within reasonable efforts. The problem is specific to portrait mode of mobile, and CSS media queries are designed specifically for this purpose, but they can't magically fit more space in less space. What they can do, though, is detect when the chart would be so narrow as to be illegible, and tell the user to switch to landscape in place of displaying a broken chart, which is basically always an immediately available alternative to portrait view, for mobile users.)

**Comment by nathanshammah** [comment]
@WrathfulSpatula I'm not an expert but testing design and size options should solve this. See snapshots below (one taken from chart.js). 

![image](https://user-images.githubusercontent.com/14573436/155703395-ff144d44-88d5-4db2-a214-62728b5f2f0c.jpeg)

![image](https://user-images.githubusercontent.com/14573436/155703405-afe2381d-bef8-465a-9dfa-da1ab4342a68.jpeg)

**Comment by WrathfulSpatula** [comment]
We detect the difference between mobile and desktop screens; for mobile, we can use the `responsive` option and set a minimum height.
