### ISSUE TITLE
Not possible to not select parent task for submission task

### ISSUE THREAD

**Issue by vprusso** [unitaryfund/metriq-app#467]
Attempting to add a new task to "Task" seems to implicitly give a parent task. It should be possible to not need to select a parent task. For instance
<img width="1249" alt="Screen Shot 2022-02-24 at 9 24 16 PM" src="https://user-images.githubusercontent.com/1562214/155641838-6eea5b32-3975-4de4-a5f9-f7525af77765.png">

**Comment by WrathfulSpatula** [comment]
@vprusso No, it should no longer be possible _not_ to select a parent task. The reason for this is that we have defined top level tasks. To keep the pre-defined top level tasks, it must not possible to create a new task without a parent, (which would make it a top level peer).

Hence, this is expected behavior. I move that we close the issue, but let me know if you have other related concerns.

**Comment by vprusso** [comment]
Ah okay that's user error on my part. I'm closing based on that. Thanks for clarifying that.
