### ISSUE TITLE
Review form complexity, to reduce

### ISSUE THREAD

**Issue by WrathfulSpatula** [unitaryfund/metriq-app#508]
Reducing form complexity, even measured in minimum depth of "clicks," is a high good in itself, in most web design. We've had a number of requests from team members to further streamline submission detail entry forms.

I can't point to specific "clicks" we might remove from the workflow off the top of my head, but we should optimize to remove any single "click" or point of data entry. @vprusso, it'd be great if you could spend some more time making submissions next week and looking for any potential optimization in reducing depth of the effective user story interaction tables, or adding more intelligent input completion features.

**Comment by vprusso** [comment]
@nathanshammah @WrathfulSpatula 

Previously, in going through a number of submissions, here are some things that could potentially be reduced or minimized either in the form of time/clicks/etc. 

Not all of these are "equal" in the sense that some of these might be of drastically more difficult complexity and some of these might be complete "non-issues" as well. In any case, writing them down here to attempt to perform a capture:

### Submission: Auto-populate description field for GitHub and arXiv content
When the user puts in either a GitHub or arXiv link the "description" section should auto-populate with content from either GitHub or the arXiv, respectively. 

This is already captured as a user story/issue here:
https://github.com/unitaryfund/metriq-app/issues/167

It's likely that we can accomplish this via the respective [GitHub API](https://docs.github.com/en/rest) and [arXiv API](https://arxiv.org/help/api/).

### Submission: Auto-upload image field for GitHub and arXiv content
When the user puts in either a GitHub or arXiv link the "image" section should automatically grab an image from the source material to include as a default image

This is already captured as an issue here:
https://github.com/unitaryfund/metriq-app/issues/121

This one is probably more difficult than just grabbing the description content--mostly because it's not clear how to decide on which image is characteristic of the submission in question. Is it the first image? etc. 

### Submission: Auto-populate tags based on prior entries

This one is definitely more complicated but it doesn't necessarily need to be particularly sophisticated. Suggested tags could be placed in the "tag box" for a given submission. Assuming one is able to parse the abstract of the arXiv or GitHub posting, the abstract could simply be parsed for any text items that align with existing tag names. These existing tag names could simply be then suggested to the user by default. 

### Submission: Formatting of text

When the user submits a submission consisting of tags (or even, a task/method/etc.) the user is in control of whether or not they choose to make the content case sensitive or not. It might be best to impose strict formatting on the input to reduce this cognitive barrier to entry for users. 

### Categorization:

This one seems to be an inactive discussion, but one point to bring up here would be that when clicking on something like "tasks", "methods", etc. the user is presented with a large collection of choices. As the number of submissions, tasks, methods, etc. grows, it will be cumbersome and difficult to scroll through large swaths of options. 

Slightly increasing the "buckets" that things can go into might be an option but might simply move the complexity to another spot. I'm not entirely sure how best to address this one. I think tasks is pretty well organized but methods can be a bit daunting to scroll through.

### Data quality parse:

One thing that might make things a bit more streamlined is combing through some of the existing submissions to improve upon some of the data quality. I think this step might be best saved for when the categorization aspect is redone though.

**Comment by WrathfulSpatula** [comment]
@vprusso Thanks for outlining this. We'll decide on items to implement, soon.
