### ISSUE TITLE
Attempting to add submission or or get API token logs user out

### ISSUE THREAD

**Issue by vprusso** [unitaryfund/metriq-app#586]
Both of these issues may be related:

#### API token re-login:

1. Log into Metriq
2. Navigate to "Account" -> "API Token"
3. The "Account" text turns to "Log in" (but the user should be logged in).

#### Submissions unauthorized

1. Log into Metriq
2. Click on "Submit" button once logged in. 
3. This yields to the "log in" page again even though the user should be logged in.
4. Fill in relevant fields
5. Attempt to submit yields "Unauthorized error"

I cleared my cookies and attempted this on two different browsers (Chrome/Firefox) but I am seeing the same issues present themselves. 

Any thoughts on that @WrathfulSpatula ? Do you happen to notice similar behavior on your end?

**Comment by WrathfulSpatula** [comment]
At first, I thought this was due to the work that resets the token expiration after every successful authenticated API route call. However, if I revert the code before that point, it _doesn't_ fix this issue. Something might have actively changed under us, about Node.js dependencies and/or browser security standards.

So, there's not a quick fix, here. I can't just roll back the code. Fixing this is top priority, though, and I hope to have a fix today.

**Comment by WrathfulSpatula** [comment]
There might have been some issue with configuration, but this should be fixed, now. Also, CORS middleware is actually not necessary in our current state of development, and it has been removed.
