### ISSUE TITLE
Add "more info" hover icons in modal

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/metriq-app#646]
Add "more info" hover icon in "add results" modal, instead of hover into on entire `span` tag.

<img width="433" alt="Screen Shot 2022-07-21 at 6 26 35 PM" src="https://user-images.githubusercontent.com/12703123/180265410-0d3c3cfe-80cc-4e29-b765-ca69ea6851b7.png">

E.g. something like https://i.stack.imgur.com/C6hIt.png, but hopefully that looks a little nicer.

**Comment by WrathfulSpatula** [comment]
We can center the hover, but I personally _hate_ hover icons, in part because they have a tiny "hitbox," and in part because _every_ label would need one: that feels like UI/UX anti-pattern, to me.

I will center (or restyle) the hover messages, though.

**Comment by WrathfulSpatula** [comment]
Nate, previously, centered form field labels were hard to read, hence the reason for left-aligned labels that don't match the tool-tip styling. However, since that decision was made, (I think over a year ago,) we've greatly improved the modal input forms. It's now not particularly hard to read, if the form field labels are centered in their column. That makes them consistent with the tool-tip alignment, while keeping the large "hitbox," so I think that's our solution.

**Comment by WrathfulSpatula** [comment]
(Actually, it's worth mentioning, this happens to make the Bootstrap work even _better_ on mobile views, because labels are responsively separated in different rows from input fields when too large, and now they're centered over the inputs, in a way we'll likely find to be aesthetic.)
