### ISSUE TITLE
Autofill from submission link isn't working.

### ISSUE THREAD

**Issue by Misty-W** [unitaryfund/metriq-app#736]
I seem to remember the submission title and description used to be autofilled upon pasting the submission link, but the autofill didn't happen on my latest submissions.

**Comment by WrathfulSpatula** [comment]
I just tried it, and it worked for me. If this happens again, it'd be great if we could have any additional details to reproduce the behavior.

**Comment by WrathfulSpatula** [comment]
@Misty-W I'm pretty sure that we found the issue in today's Metriq Weekly Jam Session: thank you for the new submissions, always, but you pointed a number of them at their direct PDF links on arXiv instead of the abstract views. Since the PDFs don't have `<meta/>` tags, the feature can't pull metadata descriptions from the links.

It only took a couple of minutes to update all such links in the database, to point to the abstract views as we prefer, so this no big deal. Thank you again for the submissions, but the prepopulation feature is definitely working for the abstract views and other links, so I'm going to go ahead and mark this issue resolved. Please reopen it, if we haven't sufficiently addressed it.

**Comment by Misty-W** [comment]
Thanks Dan, sorry for the trouble! And sorry I couldn't make it to the meeting today- unfortunately I'm still not feeling well.
