### ISSUE TITLE
Populate existing Platform in Results modal by default

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#792]
When adding a new result to this submission
https://metriq.info/Submission/460
it did show already the Task and Method that where listed on the submission, but not the Platform. Can we add the Platform, if filled out, by default?

<img width="714" alt="quantinuum-metriq" src="https://user-images.githubusercontent.com/14573436/218128681-5dd01b5c-4f2c-4822-a878-99f5ff1a3cf0.png">

Submission page:
<img width="1013" alt="Screen Shot 2023-02-10 at 16 24 25" src="https://user-images.githubusercontent.com/14573436/218129293-8f6c0d24-98b5-4eee-814f-3cd679f205e9.png">

**Comment by WrathfulSpatula** [comment]
We've added this issue to the milestone, but I want to make sure that you understand the reasoning, @nathanshammah: the platform option defaults to "(None)" because a platform is _optional_. Task and method, on the other hand, are _required_.

Speaking from experience as a web developer, I think pre-populating the platform field with an option if it exists will lead to _more_ user input mistakes, and feel _less_ intuitive, as "(None)" is a legitimate option. If you strongly disagree, please reopen the issue saying so, and I'll implement this on your say-so.
