### ISSUE TITLE
Metriq freezes from mobile browser

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#851]
Metriq freezes from mobile browser (iOS, chrome) when first going to the homepage. This was reported also by @quantshah. Specifically, one sees the first part of the homepage but cannot click on any component, starting from the cookie policy footer. The page can be surfed after reloading it multiple times.

**Comment by WrathfulSpatula** [comment]
(I have no issue loading the page on Android Chrome, by the way.)

**Comment by quantshah** [comment]
It might be a Safari browser problem on MacOS. I still get stuck when I load the page and do a refresh. Chrome loads it perfectly fine though. I am running Safari v15.5 on a MacOS Monterey v12.

**Comment by WrathfulSpatula** [comment]
I have only a single (ancient) Mac Mini device. It's running Monterrey 12.6.6 and Safari 16.5. It doesn't reproduce the issue.

@vprusso Aren't you a Mac user? I just keep an ancient Mac Mini around to publish Qrack builds, and it doesn't have a Metriq development environment, and it has a mechanical hard drive, so, even if I happened to reproduce the issue, it'd be Hell for me to fix it, on that. If you can recreate the issue, can you take a look?

**Comment by WrathfulSpatula** [comment]
@quantshah @nathanshammah It's possibly due to "single-page application" caching after publishing app updates, is a guess of mine, in which case it will naturally "cycle away" as people's caches refresh.

@vprusso If we can't reproduce, I'm not sure how we can fix it, but it might be as I said above.

**Comment by nathanshammah** [comment]
Thanks @vprusso and @WrathfulSpatula for feedback. Reopening the issue because I still experience it.


Upon reload of the page, it does not manage to fully load / update in the first instances, see snapshot below ![image](https://github.com/unitaryfund/metriq-app/assets/14573436/d354548e-c965-4c4e-8f15-100fbdf9d482)

**Comment by nathanshammah** [comment]
To clarify: After doing a couple of reloads, which though take time as the reload seems to "jam" as for the image above, then I can surf the website.

**Comment by WrathfulSpatula** [comment]
@nathanshammah Please do us a favor, because Vincent and I are "flying blind": please clear your cache for the site and try loading again on the same device.

It's always a good idea to make sure all our dependencies are met and none are unused, which is what I have done in 798057e. It'd be lucky, if that's enough to fix it, but it just might.

**Comment by WrathfulSpatula** [comment]
For unitaryHACK, to complete this bounty, first verify that you can actually locally recreate the freezing issue. (It does not happen with Vincent's or my hardware and browser.) From there, please fix it!

**Comment by WingCode** [comment]
Able to reproduce this issue on Safari 17.2.1 on MacOS
